name: kyw_management
description: ""

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Architecture
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4

  # Routes
  get: ^4.6.6

  # Dio
  dio: ^5.4.3+1

  # Envied
  envied: ^0.5.4+1

  # Programação funcional
  result_dart: ^1.1.1

  # Validator
  formz: ^0.7.0

  # Intl
  intl: ^0.19.0
  
  # Font
  google_fonts: ^6.2.1

  # Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0

  # Equatable
  equatable: ^2.0.5

  # Gap
  gap: ^3.0.1

  # Jwt_decoder
  jwt_decoder: ^2.0.1

  # UUID
  flutter_guid: ^0.3.1

  # Storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3

  # DB
  objectbox: ^4.0.1
  objectbox_flutter_libs: any

  # Path
  path_provider: ^2.1.3

  # Websocket
  stomp_dart_client: ^2.0.0
  
  flutter_localizations:
    sdk: flutter
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.10
  objectbox_generator: any

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: source
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf

